version : 2

models:
  - name: tracks
    description: "la table des tracks"
    columns:
      - name: trackid
        tests:
          - unique
          - not_null
      - name: albumid
        tests:
          - not_null
      - name: mediatypeid
        tests:
          - not_null
      - name: genreid
        tests:
          - not_null

sources:
  - name: chinook_data
    database: chinook_db
    schema: public
    tables:
      - name: tracks
      - name: artists
      - name: albums


